### ISSUE TITLE
 Given model could not be parsed while creating inference session. Error message: Protobuf parsing failed.

### ISSUE THREAD

**Issue by vladislavkoz** [abelriboulot/onnxt5#6]
Hi there, I've run a guide code and it doesn't work. 
![image](https://user-images.githubusercontent.com/40685761/90011797-e69fba00-dcaa-11ea-9454-b64356507f15.png)
I'm getting an error on the following line, 
decoder_sess, encoder_sess, tokenizer = get_encoder_decoder_tokenizer()

![image](https://user-images.githubusercontent.com/40685761/90011826-f3bca900-dcaa-11ea-864b-b0ed65f48593.png)
**text** is a text from Wikipedia about cars.

onnxt5==0.1.4
protobuf==3.6.0
python==3.7

**Comment by abelriboulot** [comment]
Hey @vladislavkoz ! Which version of onnxt5 are you running? My best bet is that the models did not download properly in the onnxt5/model_data folder.

**Comment by abelriboulot** [comment]
Hey @vladislavkoz ! Thanks for raising this.
So I have a guess as to what that might be. To start the sessions, onnxt5 first downloads and unpacks the models. If this process is incorrectly made this throws a protobuf error.
To check if it's that you can do the following:
First get the location of the package, you can simply run:
`import onnxt5
print(onnxt5.__file__)`
For me this gives /Users/abelriboulot/anaconda3/lib/python3.6/site-packages/onnxt5/__init__.py
Go to the onnxt5 package folder (in my case /Users/abelriboulot/anaconda3/lib/python3.6/site-packages/onnxt5) and cd into the model_data directory. Could you screenshot me what you see?

Then you can simply rm * and try your code again. You should see a loading bar when the models are being downloaded.

Let me know if that fixes it. If it does I might push a patch to automatically clean the model_data dir if the user has any issue.

**Comment by vladislavkoz** [comment]
![image](https://user-images.githubusercontent.com/40685761/90016059-1ef6c680-dcb2-11ea-9a4c-245b0e689111.png)
![image](https://user-images.githubusercontent.com/40685761/90016375-8dd41f80-dcb2-11ea-855c-926913fb9824.png)
After removing all from onnxt5 folder
![image](https://user-images.githubusercontent.com/40685761/90016592-e9061200-dcb2-11ea-8bb6-1cbcd3f7e4b3.png)

Then I've removed onnxt5 using pip from my env and install it again.
During the next run, I saw a progress bar and it works well now.

Here is the onnxt5 folder after reinstallation/and the first run. 
![image](https://user-images.githubusercontent.com/40685761/90017382-1f905c80-dcb4-11ea-8511-173bc104d907.png)

**Comment by vladislavkoz** [comment]
It works now. Thanks. Do you need some additional info?

**Comment by abelriboulot** [comment]
Glad it works! I think I'll patch it up to automatically delete model_data if corrupted!

**Comment by vladislavkoz** [comment]
Thanks for your fast help again.

**Comment by abelriboulot** [comment]
@vladislavkoz I pushed 0.1.5 that should take care of this issue for future users!
