### ISSUE TITLE
Default T5 summary contains <extra_id_2>.<extra_id_3>.<extra_id_4> 

### ISSUE THREAD

**Issue by vladislavkoz** [abelriboulot/onnxt5#7]
<extra_id_0> the company<extra_id_1> the company<extra_id_2>.<extra_id_3>.<extra_id_4>.<extra_id_5>.<extra_id_6>. <extra_id_7>.

Do I need some postprocessing? Or it is an issue?

**Comment by abelriboulot** [comment]
Could you show me the full example?

**Comment by vladislavkoz** [comment]
It's the full summary. What do you want me to show?

**Comment by vladislavkoz** [comment]
Here is another example:   <extra_id_0> the, and the, the first computer. The, the, was the first computer, and the

**Comment by abelriboulot** [comment]
Oh I meant can you send me your code?

**Comment by vladislavkoz** [comment]
Ohhh. My fail.  I didn't add "summarize: " prefix. It works much better now. Sorry for wasting your time.
